export const WORD_DAY_START_COIN_COST = 5
export const WORD_DAY_CLEAR_FIRST_COIN = 10
export const WORD_DAY_CLEAR_FIRST_EXP = 50
export const WORD_STAGE_CLEAR_FIRST_COIN = 50
export const WORD_STAGE_CLEAR_FIRST_EXP = 200
export const DEFAULT_DAILY_COIN_AMOUNT = 30
export const DAILY_COIN_AMOUNT_MAX = 1_000
